[project]
name = "creditscoringmle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.13.1",
    "celery==5.4.0",
    "fastapi==0.111.0",
    "httpx==0.27.0",
    "joblib==1.4.2",
    "lightgbm==4.3.0",
    "matplotlib>=3.11.1",
    "nbformat>=5.11.0",
    "numpy==1.26.4",
    "optuna==3.6.0",
    "pandas==2.2.0",
    "plotly>=6.9.0",
    "polars>=1.43.2",
    "psycopg2-binary==2.9.9",
    "pyarrow>=25.0.0",
    "pydantic==2.7.0",
    "pydantic-settings==2.3.4",
    "pytest==8.2.0",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.9",
    "redis==5.0.0",
    "scikit-learn==1.5.0",
    "seaborn>=0.13.2",
    "shap==0.45.0",
    "sqlalchemy==2.0.30",
    "uvicorn[standard]==0.30.0",
    "xgboost>=3.2.0",
]
